### Churn Prediction

##### Data - https://archive.ics.uci.edu/dataset/352/online+retail

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_excel('/Users/deepaksivas/Documents/GitHub/Retail-data-science-portfolio-/Customer Segmentation/data/Online Retail.xlsx')

In [ ]:
# pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [4]:
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [15]:
print(f"Count of Data\n{data.count()},\n\nShape{data.shape},\n \nInfo{data.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
Count of Data
InvoiceNo      541909
StockCode      541909
Description    540455
Quantity       541909
InvoiceDate    541909
UnitPrice      541909
CustomerID     406829
Country        541909
dtype: int64,

Shape(541909, 8),

InfoNone

In [14]:
data.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [35]:
data.describe(include='object')

,InvoiceNo,StockCode,Description,Country
count,541909,541909,540455,541909
unique,25900,4070,4223,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom
freq,1114,2313,2369,495478

In [ ]:
numerical_features=[feature for feature in data.columns if data[feature].dtype != 'O' and data[feature].dtype != 'datetime64[ns]']
categorical_features=[feature for feature in data.columns if data[feature].dtype == 'O']
datetime_features=[feature for feature in data.columns if data[feature].dtype == 'datetime64[ns]']
print('We have {} numerical_features:{}'.format(len(numerical_features),numerical_features))
print('We have {} categorical_features:{}'.format(len(categorical_features),categorical_features))
print('We have {} datetime_features:{}'.format(len(datetime_features),datetime_features))

We have 3 numerical_features:['Quantity', 'UnitPrice', 'CustomerID']
We have 4 categorical_features:['InvoiceNo', 'StockCode', 'Description', 'Country']
We have 1 datetime_features:['InvoiceDate']

In [31]:
data[categorical_features].nunique()
data['InvoiceNo'].head()

0    536365
1    536365
2    536365
3    536365
4    536365
Name: InvoiceNo, dtype: object

Data Description¶
Invoice: Invoice number. A unique number for each transaction. If it starts with C which means cancelled operations.

StockCode: Product code. A unique number for each product.

Description: Product name.

Quantity: It refers to how many of the products in the invoices have been sold.

InvoiceDate: Invoice date.

Price: Product price (pound)

Customer ID: Unique customer number.

Country: The name of the country where the customer lives.

### Missing values

In [34]:
total=data.isnull().sum().sort_values(ascending=False)
total

CustomerID     135080
Description      1454
InvoiceNo           0
StockCode           0
Quantity            0
InvoiceDate         0
UnitPrice           0
Country             0
dtype: int64

In [38]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [40]:
data[numerical_features]
data[categorical_features]

,InvoiceNo,StockCode,Description,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,United Kingdom
1,536365,71053,WHITE METAL LANTERN,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,United Kingdom
...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,France

In [50]:
print("StockCode have {} unique category:\n{}\n".format(data['StockCode'].nunique(),data['StockCode'].unique()))
print("Description have {} unique category:\n{}\n".format(data['Description'].nunique(),data['Description'].unique()))
print("CustomerID have {} unique category:\n{}\n".format(data['CustomerID'].nunique(),data['CustomerID'].unique()))
print("Country have {} unique category:\n{}\n".format(data['Country'].nunique(),data['Country'].unique()))
print("InvoiceNo have {} unique category:\n{}\n".format(data['InvoiceNo'].nunique(),data['InvoiceNo'].unique()))

StockCode have 4070 unique category:
['85123A' 71053 '84406B' ... '90214U' '47591b' 23843]

Description have 4223 unique category:
['WHITE HANGING HEART T-LIGHT HOLDER' 'WHITE METAL LANTERN'
 'CREAM CUPID HEARTS COAT HANGER' ... 'lost'
 'CREAM HANGING HEART T-LIGHT HOLDER' 'PAPER CRAFT , LITTLE BIRDIE']

CustomerID have 4372 unique category:
[17850. 13047. 12583. ... 13298. 14569. 12713.]

Country have 38 unique category:
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

InvoiceNo have 25900 unique category:
[536365 536366 536367 ... 581585 581586 581587]

### Pre-Processing

In [51]:
data=data.dropna(subset=['CustomerID'])

In [52]:
data.shape

(406829, 8)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

In [54]:
data['CustomerID']=data['CustomerID'].astype('str')

/var/folders/kv/02xnk4yx4q94gr1r59m8rd140000gn/T/ipykernel_60447/2704189181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['CustomerID']=data['CustomerID'].astype('str')

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  object
 7   Country      406829 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 27.9+ MB

In [63]:
# Removing the negative and zero quantity
print((data['UnitPrice']<=0).value_counts())
(data['Quantity']<=0).value_counts()

UnitPrice
False    406789
Name: count, dtype: int64

Quantity
False    397884
True       8905
Name: count, dtype: int64

- 400 entries are invalid for unitprice column

In [65]:
data=data[data['UnitPrice']>0]
data=data[data['Quantity']>0]
# data.shape

In [67]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

### RFM Metrics

RFM Attribute

<li> R(Recency): Number of days since last purchase
<li> F(Frequency) : Number of transactions
<li> M(Monetary) : Total amount of transactions(revenue contribution)

## Monetary

In [68]:
data['TotalPrice']=data['UnitPrice']*data['Quantity']
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [72]:
m_rfm=data.groupby('CustomerID')['TotalPrice'].sum()
m_rfm=m_rfm.reset_index()
m_rfm.columns=['CustomerID','Monetary']
m_rfm.head()

  CustomerID  Monetary
0    12346.0  77183.60
1    12347.0   4310.00
2    12348.0   1797.24
3    12349.0   1757.55
4    12350.0    334.40

In [70]:
m_rfm.head()

CustomerID
12346.0    77183.60
12347.0     4310.00
12348.0     1797.24
12349.0     1757.55
12350.0      334.40
Name: TotalPrice, dtype: float64

### Frequency

In [75]:
f_rfm=data.groupby('CustomerID')['InvoiceNo'].count()

In [78]:
f_rfm=f_rfm.reset_index()
f_rfm

     CustomerID  InvoiceNo
0       12346.0          1
1       12347.0        182
2       12348.0         31
3       12349.0         73
4       12350.0         17
...         ...        ...
4333    18280.0         10
4334    18281.0          7
4335    18282.0         12
4336    18283.0        756
4337    18287.0         70

[4338 rows x 2 columns]

In [80]:
f_rfm.columns=['CustomerID','Frequency']

In [81]:
f_rfm

     CustomerID  Frequency
0       12346.0          1
1       12347.0        182
2       12348.0         31
3       12349.0         73
4       12350.0         17
...         ...        ...
4333    18280.0         10
4334    18281.0          7
4335    18282.0         12
4336    18283.0        756
4337    18287.0         70

[4338 rows x 2 columns]

In [82]:
rfm=pd.merge(m_rfm,f_rfm,on='CustomerID',how='inner')
rfm.head()

  CustomerID  Monetary  Frequency
0    12346.0  77183.60          1
1    12347.0   4310.00        182
2    12348.0   1797.24         31
3    12349.0   1757.55         73
4    12350.0    334.40         17

### Recency

In [83]:
data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID             object
Country                object
TotalPrice            float64
dtype: object

### Date

In [85]:
data['InvoiceDate']

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 397884, dtype: datetime64[ns]

In [88]:
min_date=min(data['InvoiceDate'])
max_date=max(data['InvoiceDate'])
print(min_date,max_date)

2010-12-01 08:26:00 2011-12-09 12:50:00

In [90]:
data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID             object
Country                object
TotalPrice            float64
dtype: object

In [92]:
data['Diff_days']=max_date-data['InvoiceDate']

In [93]:
r_rfm=data.groupby('CustomerID')['Diff_days'].min()
r_rfm=r_rfm.reset_index()
r_rfm.columns=['CustomerID','Recency']

In [94]:
r_rfm.head()

  CustomerID           Recency
0    12346.0 325 days 02:49:00
1    12347.0   1 days 20:58:00
2    12348.0  74 days 23:37:00
3    12349.0  18 days 02:59:00
4    12350.0 309 days 20:49:00

In [95]:
r_rfm['Diff_days']=r_rfm['Recency'].dt.days
r_rfm.head()

  CustomerID           Recency  Diff_days
0    12346.0 325 days 02:49:00        325
1    12347.0   1 days 20:58:00          1
2    12348.0  74 days 23:37:00         74
3    12349.0  18 days 02:59:00         18
4    12350.0 309 days 20:49:00        309

In [107]:
rfm

,CustomerID,Monetary,Frequency,Recency_x,Diff_days_x,Recency_y,Diff_days_y
0,12346.0,77183.60,1,325 days 02:49:00,325,325 days 02:49:00,325
1,12347.0,4310.00,182,1 days 20:58:00,1,1 days 20:58:00,1
2,12348.0,1797.24,31,74 days 23:37:00,74,74 days 23:37:00,74
3,12349.0,1757.55,73,18 days 02:59:00,18,18 days 02:59:00,18
4,12350.0,334.40,17,309 days 20:49:00,309,309 days 20:49:00,309
...,...,...,...,...,...,...,...
4333,18280.0,180.60,10,277 days 02:58:00,277,277 days 02:58:00,277
4334,18281.0,80.82,7,180 days 01:57:00,180,180 days 01:57:00,180
4335,18282.0,178.05,12,7 days 01:07:00,7,7 days 01:07:00,7
4336,18283.0,2094.88,756,3 days 00:48:00,3,3 days 00:48:00,3
4337,18287.0,1837.28,70,42 days 03:21:00,42,42 days 03:21:00,42

In [103]:
rfm.describe().T
rfm.shape

(4338, 7)

In [104]:
rfm_scores=rfm.copy()

In [105]:
rfm_scores.head()

,CustomerID,Monetary,Frequency,Recency_x,Diff_days_x,Recency_y,Diff_days_y
0,12346.0,77183.60,1,325 days 02:49:00,325,325 days 02:49:00,325
1,12347.0,4310.00,182,1 days 20:58:00,1,1 days 20:58:00,1
2,12348.0,1797.24,31,74 days 23:37:00,74,74 days 23:37:00,74
3,12349.0,1757.55,73,18 days 02:59:00,18,18 days 02:59:00,18
4,12350.0,334.40,17,309 days 20:49:00,309,309 days 20:49:00,309

In [109]:
rfm_scores['R_score']=pd.qcut(rfm_scores['Recency_x'],5,labels=[5,4,3,2,1])
rfm_scores['F_score']=pd.qcut(rfm_scores['Frequency'],5,labels=[1,2,3,4,5])
rfm_scores['M_score']=pd.qcut(rfm_scores['Monetary'],5,labels=[1,2,3,4,5])

In [110]:
rfm_scores.head()

,CustomerID,Monetary,Frequency,Recency_x,Diff_days_x,Recency_y,Diff_days_y,R_score,F_score,M_score
0,12346.0,77183.60,1,325 days 02:49:00,325,325 days 02:49:00,325,1,1,5
1,12347.0,4310.00,182,1 days 20:58:00,1,1 days 20:58:00,1,5,5,5
2,12348.0,1797.24,31,74 days 23:37:00,74,74 days 23:37:00,74,2,3,4
3,12349.0,1757.55,73,18 days 02:59:00,18,18 days 02:59:00,18,4,4,4
4,12350.0,334.40,17,309 days 20:49:00,309,309 days 20:49:00,309,1,2,2

# Creating combined RFM Label

In [111]:
rfm_scores['RFM_Score']=rfm_scores['R_score'].astype(str)+rfm_scores['F_score'].astype(str)+rfm_scores['M_score'].astype(str)

In [112]:
rfm_scores.head()

,CustomerID,Monetary,Frequency,Recency_x,Diff_days_x,Recency_y,Diff_days_y,R_score,F_score,M_score,RFM_Score
0,12346.0,77183.60,1,325 days 02:49:00,325,325 days 02:49:00,325,1,1,5,115
1,12347.0,4310.00,182,1 days 20:58:00,1,1 days 20:58:00,1,5,5,5,555
2,12348.0,1797.24,31,74 days 23:37:00,74,74 days 23:37:00,74,2,3,4,234
3,12349.0,1757.55,73,18 days 02:59:00,18,18 days 02:59:00,18,4,4,4,444
4,12350.0,334.40,17,309 days 20:49:00,309,309 days 20:49:00,309,1,2,2,122

In [113]:
## RFM score sum

rfm_scores['RFM_Score_sum']=rfm_scores['R_score'].astype(int)+rfm_scores['F_score'].astype(int)+rfm_scores['M_score'].astype(int)

In [114]:
rfm_scores.head()

,CustomerID,Monetary,Frequency,Recency_x,Diff_days_x,Recency_y,Diff_days_y,R_score,F_score,M_score,RFM_Score,RFM_Score_sum
0,12346.0,77183.60,1,325 days 02:49:00,325,325 days 02:49:00,325,1,1,5,115,7
1,12347.0,4310.00,182,1 days 20:58:00,1,1 days 20:58:00,1,5,5,5,555,15
2,12348.0,1797.24,31,74 days 23:37:00,74,74 days 23:37:00,74,2,3,4,234,9
3,12349.0,1757.55,73,18 days 02:59:00,18,18 days 02:59:00,18,4,4,4,444,12
4,12350.0,334.40,17,309 days 20:49:00,309,309 days 20:49:00,309,1,2,2,122,5